plugins:
  - rubocop-rspec

AllCops:
  Exclude:
    - 'vendor/**/*'
  NewCops: enable
  TargetRubyVersion: 3.1

Naming/FileName:
  Exclude:
    - 'lib/jira-ruby.rb'

Naming/MethodName:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - 'spec/**/*'

##
# Temporarily Disable
# 
# We are going to disable these and fix in pull requests
##
Layout/LineLength:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: false

Lint/EmptyClass:
  Enabled: false

Lint/IneffectiveAccessModifier:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Naming/PredicateName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/ExpectInHook:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/LeakyConstantDeclaration:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/ReceiveMessages:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

RSpec/SubjectStub:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

Style/MissingRespondToMissing:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false
